// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrgzehtjzicoymhualsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyZ3plaHRqemljb3ltaHVhbHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2ODk4MTAsImV4cCI6MjA2MzI2NTgxMH0.SyoFF3jc_Zu_tZKhkUFfaXvre-fekO7oa1IDHX4kr7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);